### ISSUE TITLE
Support scheme specific console scripts

### ISSUE THREAD

**Issue by FFY00** [pradyunsg/installer#37]
Currently, the console scripts will run with the site module imported, this is what we want in a general case, but there are some cases where that may not be. As part of the distutils deprecation, we are planning to add a officially supported way for Python distributor to specify custom schemes, like Debian's dist-packages. This would allow distributors to install their packages outside site-packages, to avoid conflicts. It would be really helpful if we could also generate console scripts that will only use specific schemes, preventing pip install/uninstall from shadowing packages that distro scripts expect to be there. Overall, I think this would provide a better UX for users, as it would make their system significantly harder to break.
As part of this mechanism, I would propose adding a way to easily achieve what I am asking here.

Would this be something we could maybe consider supporting? Preferabily in the CLI also.

**Comment by pradyunsg** [comment]
> As part of the distutils deprecation, we are planning to add a officially supported way for Python distributor to specify custom schemes, like Debian's dist-packages.

Who is "we" here, and where is this discussion taking place?

---

The way the abstractions are designed in this library, it should be possible for folks to implement a custom `WheelDestination` that behaves however they want. If someone wants to implement the abstraction with the sort of behaviour you're envisioning, please feel free to!

To set expectations here, I imagine a change like this needs sysconfig changes, and some sort of public design discussion about this (likely a discuss.python.org thread). I won't add something for this in this libary until _after_ we have concensus that this mechanism is how we want to solve the "make it harder to break the system" problem.

**Comment by FFY00** [comment]
> Who is "we" here, and where is this discussion taking place?

The discussion about this has been happening in PyPA Discord channel and is between me and @jaraco.

> The way the abstractions are designed in this library, it should be possible for folks to implement a custom `WheelDestination` that behaves however they want. If someone wants to implement the abstraction with the sort of behaviour you're envisioning, please feel free to!

Of course, I was just opening this as "it would be good to have it here instead of me having to design a custom CLI".

> To set expectations here, I imagine a change like this needs sysconfig changes, and some sort of public design discussion about this (likely a discuss.python.org thread). I won't add something for this in this libary until _after_ we have concensus that this mechanism is how we want to solve the "make it harder to break the system" problem.

Yes, absolutely. I did not clarify, but my reasoning behind this issue was to gather if this is something that you would consider supporting here, as I am not entirely sure of the scope and extent you plan to give this project. But yeah, this would only happen if we added a proper mechanism to Python itself.

**Comment by pradyunsg** [comment]
Coolieo!

> my reasoning behind this issue was to gather if this is something that you would consider supporting here, as I am not entirely sure of the scope and extent you plan to give this project.

Assuming this is a standard mechanism that we expect "most installation tools" to implement, I'd be happy to add something for it. What that'll look like, depends on what the mechanism looks like. :)

If you don't have any follow up questions here, please feel free to close this. :)

**Comment by pradyunsg** [comment]
Closing since no follow up questions were asked! :)

**Comment by FFY00** [comment]
Actually, we already have a way to do this.

We just need to pass `-S` to the interpreter, to prevent the site module initialization to happen, and add the site dirs we want in the entrypoint script.

```python
site.addsitedir(sysconfig.get_path('purelib', scheme))
site.addsitedir(sysconfig.get_path('platlib', scheme))
```

**Comment by FFY00** [comment]
But of course, it only makes sense if the proposed changes go it.

**Comment by pradyunsg** [comment]
> What "PyPA Discord channel"?

Someone made a Discord channel with the PyPA logo at some point, IIUC.

**Comment by FFY00** [comment]
@gaborbernat made the channel, we have channels for a few projects and a few maintainers. The link is available in the readme/documentation of a few projects like virtualenv and pypa/build, and IIRC there was some talk about adding it pypa website but I can't recall if that was ever proposed.

https://discord.gg/pypa
