### ISSUE TITLE
Implement `installer.sources.WheelFile`

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/installer#48]
> I can't see in the code the `WheelFile` class which the docs landing page mentions - is that still to come?

_Originally posted by @takluyver in https://github.com/pradyunsg/installer/issues/1#issuecomment-827412319_

Yes. This is the last big remaining TODO as far as I can tell.

**Comment by FFY00** [comment]
Are you working on it, or can I do it? I need it for my CLI.

**Comment by pradyunsg** [comment]
Working on this right now. :)
