### ISSUE TITLE
Make `SchemeDictionaryDestination._write_file` public

### ISSUE THREAD

**Issue by FFY00** [pradyunsg/installer#49]
Hey, I am implementing a CLI and need to have a `destdir` option that allows me to relocate the install root to an arbitrary path. This is used when building distro packages for example, because we want to put the files in the package directory instead of on the system. This analogous to the `setup.py install --root` option.

Would it be possible to make `SchemeDictionaryDestination._write_file` public so that I can simply overwrite it, instead of having to overwrite `write_file` and `write_script`.
I recommend renaming it to `write_to_fs`, what do you think?

**Comment by pradyunsg** [comment]
The caller provides the paths used, via `SchemeDictionaryDestination.__init__`. You should be able to change that's passed in, to control where the files end up.

**Comment by pradyunsg** [comment]
Just had a chat with @FFY00 over on the PyPA Discord (https://discuss.python.org/t/theres-a-pypa-discord-now/8515) -- he wants the RECORD file to contain a different path from where the files get installed. This behaviour would live outside this library (in a custom implementation of the `WheelDestination`).

In general, folks might wanna handle the I/O differently or do weird things like this, so having a clearly documented `write_to_fs` won't hurt anyone. :)

**Comment by FFY00** [comment]
Yeah, this is my implementation.

```python
class TunableSchemeDictionaryDestination(SchemeDictionaryDestination):
    '''Scheme mapping based destination with support for changing the destination root (destdir)'''

    def __init__(
        self,
        scheme_dict,
        interpreter,
        script_kind,
        hash_algorithm="sha256",
        destdir=None,
    ):
        # type: (Dict[str, str], str, LauncherKind, str, Optional[FSPath]) -> None
        super().__init__(scheme_dict, interpreter, script_kind, hash_algorithm)
        self._destdir = destdir

    def write_to_fs(self, scheme, path, stream):
        # type: (Scheme, FSPath, BinaryIO) -> RecordEntry
        target_path = os.path.join(self.scheme_dict[scheme], path)
        if self._destdir:
            target_path = os.path.join(self._destdir, target_path)
        # open(..., "x") is not supported in Python 2 so let's check if a file is there ourselves
        if os.path.exists(target_path):
            raise FileExistsError(
                'Target file already exists in the file-system: {}'.format(target_path)
            )
        with open(target_path, 'wb') as f:
            hash_, size = copyfileobj_with_hashing(stream, f, self.hash_algorithm)
        return RecordEntry(path, Hash(self.hash_algorithm, hash_), size)
```
