### ISSUE TITLE
Provide a CLI

### ISSUE THREAD

**Issue by flying-sheep** [pradyunsg/installer#52]
As mentioned in #1 and the description, it would be useful to have a CLI. (Creating this so people can get notified)

My use case for this project is to replace the way Linux distribution packages are packaged. As Thomas said in https://github.com/pradyunsg/installer/issues/1#issuecomment-622970860, people currently use error prone command lines like this:

```bash
python -m pip install --root $RPM_BUILD_ROOT --no-deps --disable-pip-version-check --progress-bar off --verbose --ignore-installed --no-warn-script-location pyproject-wheeldir/*.whl
```

Would be great to have a very simple command line that does exactly that: Given a

- Python binary with version `$pythonver`,
- `$root` directory, and
- wheel file

it installs the

- package and dist info to `$root/usr/lib/python$pythonver/site-packages/`,
- headers to `$root/usr/include/`,
- scripts to `$root/usr/bin/`, and
- data to `$root` (I assume)

**Comment by FFY00** [comment]
@pradyunsg has said the `$root` feature (aka `destdir`) is out of scope. Though I really hope he would reconsider. This is a basic feature in any kind of installer, and without it packagers cannot use this tool.

https://www.gnu.org/prep/standards/html_node/DESTDIR.html

All we need is literally this:
```patch
diff --git a/src/installer/destinations.py b/src/installer/destinations.py
index 9e4192d..3360733 100644
--- a/src/installer/destinations.py
+++ b/src/installer/destinations.py
@@ -15,7 +15,7 @@ from installer.utils import (
 )
 
 if TYPE_CHECKING:
-    from typing import BinaryIO, Dict, Iterable
+    from typing import BinaryIO, Dict, Iterable, Optional
 
     from installer._compat.typing import FSPath, Text
     from installer.scripts import LauncherKind, ScriptSection
@@ -79,8 +79,9 @@ class SchemeDictionaryDestination(WheelDestination):
         interpreter,
         script_kind,
         hash_algorithm="sha256",
+        destdir=None,
     ):
-        # type: (Dict[str, str], str, LauncherKind, str) -> None
+        # type: (Dict[str, str], str, LauncherKind, str, Optional[FSPath]) -> None
         """Construct a ``SchemeDictionaryDestination`` object.
 
         :param scheme_dict: a mapping of {scheme: file-system-path}
@@ -89,16 +90,20 @@ class SchemeDictionaryDestination(WheelDestination):
         :param hash_algorithm: the hashing algorithm to use, which is a member
             of :any:`hashlib.algorithms_available` (ideally from
             :any:`hashlib.algorithms_guaranteed`).
+        :param destdir: destination path prefix
         """
         self.scheme_dict = scheme_dict
         self.interpreter = interpreter
         self.script_kind = script_kind
         self.hash_algorithm = hash_algorithm
+        self.destdir = destdir
 
     def write_to_fs(self, scheme, path, stream):
         # type: (Scheme, FSPath, BinaryIO) -> RecordEntry
         """Write a file to the file-system."""
         target_path = os.path.join(self.scheme_dict[scheme], path)
+        if self.destdir:
+            target_path = os.path.join(self.destdir, target_path)
         # open(..., "x") is not supported in Python 2 so let's check if a file is there ourselves
         if os.path.exists(target_path):
             raise FileExistsError(
```

---

The actual paths are given by your Python installation, so all that should be correct.

**Comment by pradyunsg** [comment]
(retitled, because IMO this isn't tracking the actual implementation task and is an open discussion)

**Comment by FFY00** [comment]
Please read the link I sent. Essentially in packaging we install the files to a custom folder and then tarball it and call it a package.
I did check and actually this path doesn't go to RECORD, it takes relative paths to the purelib/platlib root.

**Comment by pradyunsg** [comment]
> Please read the link I sent.

I had before I wrote the comment you're responding to. :) 

---

I'll rephrase my question, if you're installing under a different prefix, why do you NOT want the RECORD to reflect that prefix?

As an example, do object files containing the debug information not contain that prefix in filenames?

**Comment by flying-sheep** [comment]
An additional reason is reproducibility: When using a staged build, the exact same bytes should be produced, independently of the path of the build directory.

**Comment by pradyunsg** [comment]
@FFY00 I still don't think destdir support needs to be baked into any Destination object?

```py
def prefix_with_destdir(path: str) -> str:
    return os.path.join(my_destdir, path.lstrip("/"))


schemes = {key: prefix_with_destdir(value) for key, value in sysconfig.get_config_vars()}
interpreter = prefix_with_destdir(sys.executable)
my_destdir_destination = SchemeDictDestination(schemes, interpreter, "posix")
```

**Comment by pradyunsg** [comment]
I'm gonna move the whole conversation about destdir to #58, and hide all the comments related to it here as off-topic.

**Comment by FFY00** [comment]
One other desirable feature would be dependency checking. https://github.com/FFY00/build provides a function for this, if you want to use it.

https://github.com/pypa/build/blob/9258bccd200bf02ff101abde5f8d39d0e88cc621/src/build/__init__.py#L84

**Comment by pradyunsg** [comment]
This is done, with #94.

**Comment by flying-sheep** [comment]
Yay! This is so beautiful. I couldn’t wait and made a git package to try it out: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-installer-git

An arch PKGBUILD for a Python package can now look like:

```zsh
pypiname=...
pkgname=python-$pypiname
pkgver=...
[…]
makedepends=(python-build python-installer)  # nothing more

build() {
	cd "$srcdir/$pkgname-$pkgver"
	python -m build -w
}

package() {
	cd "$srcdir/$pkgname-$pkgver"
	python -m installer -d "$pkgdir" "dist/$pypiname-$pkgver-py3-none-any.whl"
}
```
