### ISSUE TITLE
Drop outdated link to importlib_metadata in comment

### ISSUE THREAD

**Issue by pradyunsg** [pradyunsg/installer#64]
Is this comment still up-to-date @pradyunsg? The linked target is entirely different from the code below.

_Originally posted by @uranusjr in https://github.com/pradyunsg/installer/pull/63#discussion_r655209531_

**Comment by domdfcoding** [comment]
Didn't this end up getting resolved by https://github.com/pradyunsg/installer/commit/7671f98e1710116d2c370942e876f6b1c162bace (part of #63)?

**Comment by pradyunsg** [comment]
Indeed!
