### ISSUE TITLE
The executable bit is lost for scripts in data directory

### ISSUE THREAD

**Issue by frostming** [pradyunsg/installer#68]
`installer` seems only to copy streams and won't copy the executable bit when installing

**Comment by FFY00** [comment]
Oh, right, because we only work with streams for the abstraction. We will have to add something for the permissions/mode. Do we need this in anything other than the user-provided scripts? If not, would it be reasonable to set the executable on all installed scripts?

**Comment by FFY00** [comment]
Nevermind, users can ship executable as package resources :sweat_smile:

**Comment by pradyunsg** [comment]
Got an example zip file for this?

**Comment by uranusjr** [comment]
No example but this is where pip handles the permission bits.

https://github.com/pypa/pip/blob/0f21fb920647f07439c3ec9fb29579c0e00072ec/src/pip/_internal/operations/install/wheel.py#L656-L663

https://github.com/pypa/pip/blob/0f21fb920647f07439c3ec9fb29579c0e00072ec/src/pip/_internal/utils/unpacking.py#L43-L47

**Comment by pradyunsg** [comment]
Ah, this is the stuff that is missing:

https://github.com/pypa/pip/blob/0f21fb920647f07439c3ec9fb29579c0e00072ec/src/pip/_internal/utils/unpacking.py#L88

https://github.com/pypa/pip/blob/0f21fb920647f07439c3ec9fb29579c0e00072ec/src/pip/_internal/utils/unpacking.py#L96

**Comment by pradyunsg** [comment]
I've got a patch for this in https://github.com/pradyunsg/installer/commit/d2cd48404d084997541d1f12c2623ad30279cfb3, since I wrote that as part of #74. Gonna split that out though, since that's unrelated to that broader PR.
